name: Upload to S3

on:
  release:
    types: [ published  ]

jobs:
  upload:
    name: Uploading
    runs-on: "ubuntu-latest"
    steps:
      - name: Get the release assets info
        uses: kennylindley/get-release-info@master
        with:
          matching_regex: ^(?:Simple-In-Out-)[0-9]+\.[0-9]+\.[0-9]+\.(?:dmg|exe)$
        id: get_info

      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: "Download files using the release URLs received earlier"
        run: |
          for i in $(echo ${{ steps.get_info.outputs.urls }} | sed "s/,/ /g")
          do
            curl $i
          done

      - name: "Copy file to S3 bucket"
        run: "aws s3 sync . s3://$AWS_S3_BUCKET/${{ steps.get_info.outputs.version }}"
        env:
          AWS_S3_BUCKET: simpleinout-releases
